### ISSUE TITLE
Sync arch packages with the `PKGBUILD` from tyhe official repos

### ISSUE THREAD

**Issue by FFY00** [1138-4EB/ghdl-packaging#1]
The current packages are doing a lot of wrong things, I suggest you base them on the `PKGBUILD` from the official repos. I can point out what is wrong if you want.

**Comment by FFY00** [comment]
The MinGW packages would also benefit from some of the changes.

**Comment by eine** [comment]
I cherry-picked the commits from #2. As commented in https://github.com/eine/ghdl-packaging/pull/2#issuecomment-662559259, separated packages are preserved.

At the same time, MINGW packages have been updated according to https://github.com/ghdl/ghdl/tree/master/dist/msys2-mingw, msys2/MINGW-packages#5757, msys2/MINGW-packages#6686 and msys2/MINGW-packages#6688.

Nonetheless, do not hesitate to point out issues which you might still find wrong.
